language: minimal

git:
  depth: 1

os:
  - linux

before_install:
  - Cuis-Smalltalk-Dev/.ContinuousIntegrationScripts/installVm.sh
  - sh .ContinuousIntegrationScripts/installCuis.sh

script:
  - .ContinuousIntegrationScripts/runTests.sh
