language: minimal

git:
  depth: 1

os:
  - linux
  - osx

before_install:
  - Cuis-Smalltalk-Dev/.ContinuousIntegrationScripts/installVm.sh
  - .ContinuousIntegrationScripts/installCuis.sh

script:
  - .ContinuousIntegrationScripts/runTests.sh
