
language: python
python:
  - "3.6"
git:
  depth: false

os:
  - linux

before_install:
  - git checkout main
  - Cuis-Smalltalk-Dev/.ContinuousIntegrationScripts/installVm.sh
  - travis_wait 30 sh .ContinuousIntegrationScripts/installCuis.sh

script:
  - sh .ContinuousIntegrationScripts/runTests.sh
  - sh .ContinuousIntegrationScripts/push_to_mega.sh
