language: minimal

git:
  depth: 1

os:
  - linux
  - osx

before_install:
  - .ContinuousIntegrationScripts/installVm.sh
  - .ContinuousIntegrationScripts/installUpdates.sh

script:
  - .ContinuousIntegrationScripts/runTests.sh
